# Generated by Django 5.2.11 on 2026-02-24 20:21

from django.db import migrations

from user.emums import UserRoleChoices
from django.contrib.auth import get_user_model

DATA = [
    {
        "email": "admin@mail.com",
        "password": "admin",
        "full_name": "admin",
        "role": UserRoleChoices.ADMIN,
        "is_superuser": True,
        "is_staff": True,
    },
    {
        "email": "caregiver@mail.com",
        "password": "caregiver",
        "full_name": "caregiver",
        "role": UserRoleChoices.CAREGIVER,
        "is_staff": True,
    },
    {
        "email": "patient@mail.com",
        "password": "patient",
        "full_name": "patient",
        "role": UserRoleChoices.PATIENT,
    },
]


def create_new_users(apps, schema_editor):
    User = get_user_model()

    for item in DATA:
        User.objects.create_user(**item)


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_new_users, reverse_code=migrations.RunPython.noop),
    ]
