# Generated by Django 5.2.11 on 2026-02-25 07:09

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('duty', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated_at')),
                ('archived_stamp', models.DateTimeField(blank=True, null=True, verbose_name='archived_stamp')),
                ('number', models.CharField(max_length=10, unique=True)),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('missed', 'Missed')], default='scheduled')),
                ('description', models.CharField(max_length=500)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_visits', to=settings.AUTH_USER_MODEL)),
                ('duties', models.ManyToManyField(to='duty.duty')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'visits',
                'indexes': [models.Index(fields=['status', 'start_date_time'], name='idx_status_start'), django.contrib.postgres.indexes.GinIndex(fields=['number'], name='ix_number_trgm', opclasses=['gin_trgm_ops'])],
            },
        ),
    ]
