# Generated by Django 5.2.11 on 2026-02-25 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated_at')),
                ('archived_stamp', models.DateTimeField(blank=True, null=True, verbose_name='archived_stamp')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.DurationField()),
            ],
            options={
                'db_table': 'duties',
            },
        ),
        migrations.CreateModel(
            name='DutyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated_at')),
                ('archived_stamp', models.DateTimeField(blank=True, null=True, verbose_name='archived_stamp')),
                ('status', models.CharField(choices=[('done', 'Done'), ('not_done', 'Not Done')])),
                ('duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duty.duty')),
            ],
            options={
                'db_table': 'duty_results',
            },
        ),
    ]
