# Generated by Django 5.2.11 on 2026-02-25 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('duty', '0001_initial'),
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutyresult',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_results', to='visit.visit'),
        ),
    ]
