# Generated by Django 5.2.11 on 2026-02-24 20:15
from datetime import timedelta

from django.db import migrations


def create_new_duties(apps, schema_editor):
    Duty = apps.get_model("duty", "Duty")

    duties = []

    for i in range(1, 10):
        duty = Duty(name=f"Duty #{i}", duration=timedelta(minutes=i * 10))
        duties.append(duty)

    Duty.objects.bulk_create(duties)


class Migration(migrations.Migration):

    dependencies = [
        ("duty", "0002_initial"),
    ]

    operations = [
        migrations.RunPython(create_new_duties, reverse_code=migrations.RunPython.noop),
    ]
